import React, { useContext } from 'react';

import Head from 'next/head'
import Cards from "../components/Cards";
import Carts from "./Carts";
import Favorite from "./Favorite";
import contexts from "../context/contexts.js";
import Link from 'next/link'
import Cart from './Cart';


const Home = (props) => {
  const context = useContext(contexts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Cards type={context.AllBeers}/>
    </>
  )
}


export default Home;
